import React from 'react';
import type { Metadata } from 'next';

import Header from '@/components/moleclues/header/Header';
import { Provider } from '@/lib/tanstack-query/QueryProvider';

import '@/styles/global.css';
import { pretendard } from '../../public/fonts/pretendard';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={`${pretendard.variable}`}>
      <body>
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
